FROM python:3.9
EXPOSE 20001/udp
EXPOSE 20010/tcp
EXPOSE 20011/tcp
EXPOSE 20012/tcp
EXPOSE 20013/tcp
RUN pip install pycryptodome
RUN pip install numpy
COPY Server/SQL-Scripts/create_tables.sql Server/SQL-Scripts/create_tables.sql
COPY Server/SQL-Scripts/create_example_customers.sql Server/SQL-Scripts/create_example_customers.sql
ADD Server/Server_Main.py Server/DB_Interface.py Server/Sessions.py Server/CustomerService.py Server/CardTerminalService.py Utils.py .
CMD ["python", "Server_Main.py"]
